// src/pages/addSubsonic.tsx
import { Button, Card, Flex, FormControl, FormErrorMessage, FormLabel, Input, Text, VStack } from "@chakra-ui/react";
import { t } from "i18next";
import { useNavigate } from "react-router-dom";
import { history } from "../helpers/history";
import { TbSubmarine } from "react-icons/tb";
import { invoke } from "@tauri-apps/api/tauri";
import { toast } from 'react-toastify';
import { Field, Formik } from "formik";

function AddSubsonic() {
    const navigate = useNavigate();

    function onBackClick() {
        navigate(history.location?.pathname ?? "/firstrun");
    }

    async function handleAddSubsonicSubmit(values: {
        host: string;
        username: string;
        password: string;
    }) {
        const host = values.host;
        const username = values.username;
        const password = values.password;

        var correctCreds = await invoke("check_credentials", { provider: "Subsonic", host, username, password }) as unknown as boolean

        if (!correctCreds) {
            toast.error(t('InvalidCredentials'));
            return;
        }

        try {
            var addedProvider = await invoke("add_provider", { provider: "Subsonic", host, username, password }) as any
        }
        catch (exception) {
            console.log(exception)
        }

        if (addedProvider) {
            navigate("/firstrun")
        }
    }

    return (
        <>
            <Flex align="center" justify="center" h="100vh">
                <Card sx={{ height: 'auto%', width: '75%', margin: 'auto' }}>
                    <Text sx={{ textAlign: "center", fontSize: 50, marginTop: 5 }}><TbSubmarine /> Subsonic</Text>
                    <Formik
                        initialValues={{
                            host: "",
                            username: "",
                            password: ""
                        }}
                        onSubmit={handleAddSubsonicSubmit}
                    >
                        {({ handleSubmit, errors, touched }) => (
                            <form onSubmit={handleSubmit}>
                                <VStack spacing={4} align="flex-start">
                                    <FormControl isInvalid={!!errors.host && touched.host}>
                                        <FormLabel htmlFor="host">{t('Host')}</FormLabel>
                                        <Field
                                            as={Input}
                                            color="black"
                                            id="host"
                                            name="host"
                                            type="text"
                                            variant="filled"
                                            validate={(value: string) => {
                                                let error;

                                                if (value.length === 0) {
                                                    error = t("FieldRequired") //TODO translate
                                                }

                                                return error;
                                            }} />
                                        <FormErrorMessage>{errors.host}</FormErrorMessage>
                                    </FormControl>
                                    <FormControl>
                                        <FormLabel htmlFor="username">{t('Username')}</FormLabel>
                                        <Field
                                            as={Input}
                                            color="black"
                                            id="username"
                                            name="username"
                                            type="text"
                                            variant="filled"
                                            validate={(value: string) => {
                                                let error;

                                                if (value.length === 0) {
                                                    error = t("FieldRequired") //TODO translate
                                                }

                                                return error;
                                            }} />
                                        <FormErrorMessage>{errors.username}</FormErrorMessage>
                                    </FormControl>
                                    <FormControl>
                                        <FormLabel htmlFor="password">{t('Password')}</FormLabel>
                                        <Field
                                            as={Input}
                                            color="black"
                                            id="password"
                                            name="password"
                                            type="password"
                                            variant="filled"
                                            validate={(value: string) => {
                                                let error;

                                                if (value.length === 0) {
                                                    error = t("FieldRequired") //TODO translate
                                                }

                                                return error;
                                            }} />
                                        <FormErrorMessage>{errors.password}</FormErrorMessage>
                                    </FormControl>
                                    <Button type="submit" colorScheme="blue" width="full">
                                        {t('Add')}
                                    </Button>
                                </VStack>
                            </form>
                        )}
                    </Formik>

                </Card>
            </Flex>
            <Flex position="fixed" bottom="10" left="10">
                <Button colorScheme="blue" onClick={onBackClick}>
                    {t('Back')}
                </Button>
            </Flex>
        </>
    );
}

export default AddSubsonic;

// src/views/AddSubsonic.vue
<template>
    <div class="w-full flex flex-col">
        <div class="container justify-center m-auto items-center">
            <div class="card bg-neutral shadow">
                <div class="card-body">
                    <h1 class="card-title justify-center font-bold text-5xl"><v-icon name="gi-submarine"
                            class="w-14 h-14" />Subsonic</h1>
                    <Form class="flex flex-col justify-center items-center" :validationSchema="validationSchema"
                        @submit="handleSubmit">
                        <Field name="host" placeholder="host" class="input input-bordered w-full max-w-xs mb-2">
                        </Field>
                        <div class="w-[45%] mb-4">
                            <ErrorMessage name="host" class="text-secondary" />
                        </div>
                        <Field name="username" :placeholder="$t('Username')"
                            class="input input-bordered w-full max-w-xs mb-2"></Field>
                        <div class="w-[45%] mb-4">
                            <ErrorMessage name="username" class="text-secondary" />
                        </div>
                        <Field type="password" name="password" :placeholder="$t('Password')"
                            class="input input-bordered w-full max-w-xs mb-2"></Field>
                        <div class="w-[45%] mb-4">
                            <ErrorMessage name="password" class="text-secondary" />
                        </div>
                        <button type="submit" class="btn btn-primary">
                            <div v-if="!loading">{{ $t('Add') }}</div>
                            <div v-else><span class="loading loading-spinner"></span></div>
                        </button>
                    </Form>
                </div>
            </div>
        </div>
        <!-- Back button left bottom -->
        <div class="fixed bottom-0 left-0 p-4">
            <button class="btn btn-primary" @click="router.back()">{{ $t('Back') }}</button>
        </div>
    </div>
</template>

<script setup lang="ts">
import { Form, Field, ErrorMessage } from 'vee-validate';
import { useRouter } from 'vue-router';
import { toTypedSchema } from '@vee-validate/yup';
import { InferType, object, string } from 'yup';
import { ref } from 'vue';
import { invoke } from '@tauri-apps/api/core';
import { useToast } from 'vue-toastification';
import { useI18n } from 'vue-i18n';

const loading = ref(false);
const router = useRouter();
const toast = useToast();
const i18n = useI18n();

const schema = object({
    host: string().required(i18n.t("FieldRequired")),
    username: string().required(i18n.t("FieldRequired")),
    password: string().required(i18n.t("FieldRequired")),
});

const validationSchema = toTypedSchema(schema);

const handleSubmit = async (values: unknown, { resetForm }: { resetForm: () => void }) => {
    const formValues = values as InferType<typeof schema>;

    loading.value = true;

    if (!await invoke<boolean>("check_credentials", { provider: "Subsonic", host: formValues.host, username: formValues.username, password: formValues.password })) {
        toast.error(i18n.t('InvalidCredentials'));
        loading.value = false;
        return;
    }

    try {
        var addedProvider = await invoke("add_provider", { provider: "Subsonic", host: formValues.host, username: formValues.username, password: formValues.password });
    } catch (e) {
        console.error("Err response", e);
        toast.error("Error")
        loading.value = false;
        return;
    }

    console.log("Added", addedProvider);
    if (addedProvider) {
        resetForm();
        router.push('/firstRun');
    }
    loading.value = false;
};
</script>
